### ISSUE TITLE
NuProcess start 1.0.3 fails on Windows 

### ISSUE THREAD

**Issue by clidev** [brettwooldridge/NuProcess#41] opened 2015-09-14 09:46 UTC
I'm unable to get 1.0.3 to work on Windows 7 (64-bit). It seems like NuProcess fails to create a process on Windows. The same test code works on Windows 7 with NuProcess 0.9.7.

Here's the stacktrace:
io.spikex.core.util.unit.ProcessTest > testCommandOutput STANDARD_ERROR
    java.lang.RuntimeException: CreateProcessW() failed, error: 2
        at com.zaxxer.nuprocess.windows.WindowsProcess.start(WindowsProcess.java:251)
        at com.zaxxer.nuprocess.windows.WinProcessFactory.createProcess(WinProcessFactory.java:42)
        at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:240)
        at io.spikex.core.util.process.ProcessExecutor.start(ProcessExecutor.java:115)

**Comment by clidev** [comment] 2015-09-17 19:30
I'm able to repeat the problem with the simple example code below. 

```java
package nuprocesstestwin7;

import com.zaxxer.nuprocess.NuProcess;
import com.zaxxer.nuprocess.NuProcessBuilder;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class NuProcessTestWin7 {

    public static void main(String[] args) {
        try {
            // Display JVM info
            System.out.println(System.getProperty("java.vendor")
                    + " " + System.getProperty("java.version"));
            // Display OS info
            System.out.println(System.getProperty("os.name")
                    + " " + System.getProperty("os.version")
                    + " (" + System.getProperty("os.arch") + ")");
            // Test output of DIR command
            NuProcessBuilder pb = new NuProcessBuilder("cmd.exe /c echo hi");
// This does not work either:
//            NuProcessBuilder pb = new NuProcessBuilder("cmd.exe", "/c", "echo hi");
            ProcessHandler handler = new ProcessHandler();
            pb.setProcessListener(handler);
            NuProcess process = pb.start();
            process.wantWrite();
            process.waitFor(0, TimeUnit.SECONDS); // when 0 is used for waitFor() the wait is infinite
        } catch (InterruptedException ex) {
            Logger.getLogger(NuProcessTestWin7.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
```

This gives the following output:

```
Oracle Corporation 1.8.0_40
Windows 7 6.1 (amd64)
java.lang.RuntimeException: CreateProcessW() failed, error: 2
	at com.zaxxer.nuprocess.windows.WindowsProcess.start(WindowsProcess.java:255)
	at com.zaxxer.nuprocess.windows.WinProcessFactory.createProcess(WinProcessFactory.java:42)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at nuprocesstestwin7.NuProcessTestWin7.main(NuProcessTestWin7.java:25)
Exception in thread "main" java.lang.NullPointerException
	at com.zaxxer.nuprocess.windows.WindowsProcess.wantWrite(WindowsProcess.java:167)
	at nuprocesstestwin7.NuProcessTestWin7.main(NuProcessTestWin7.java:26)
```

The culprit seems to be the `WindowsCreateProcessEscape` class that quotes command line arguments. 

WindowsProcess.getCommandLine
```java
   private char[] getCommandLine(List<String> commands)
   {
      StringBuilder sb = new StringBuilder();
      for (String command : commands) {
         // It's OK to apply CreateProcess escaping to even the first item in the commands
         // list (the path to execute). Since Windows paths cannot contain double-quotes
         // (really!), the logic in WindowsCreateProcessEscape.quote() will either do nothing
         // or simply add double-quotes around the path.
         WindowsCreateProcessEscape.quote(sb, command);
      }
      return Native.toCharArray(sb.toString());
   }
```

The following simple solution seems to work at least for trivial commands:

```java
   private char[] getCommandLine(List<String> commands)
   {
      StringBuilder sb = new StringBuilder();
      for (String command : commands) {
         // It's OK to apply CreateProcess escaping to even the first item in the commands
         // list (the path to execute). Since Windows paths cannot contain double-quotes
         // (really!), the logic in WindowsCreateProcessEscape.quote() will either do nothing
         // or simply add double-quotes around the path.
         //WindowsCreateProcessEscape.quote(sb, command);
         // Simply bypass quoting and add extra space
         // A more rigorous solutions is needed though...
         sb.append(command);
         sb.append(" ");
      }
      return Native.toCharArray(sb.toString());
   }
```

Maybe it would be advantageous to let the caller decide if any fancy argument quoting is needed.

**Comment by brettwooldridge** [comment] 2015-09-18 04:18
@clidev @bhamiltoncx Is it the case that ``NuProcessTestWin7`` runs successfully on 0.9.7?  If so, my preferred course of action would be to revert the ``getCommandLine()`` code to 0.9.7, rather than adding a system property to disable escaping.

I probably should have questioned the sweeping nature of 630de23 at the outset.

**Comment by brettwooldridge** [comment] 2015-09-18 04:26
@clidev Re: "Maybe it would be advantageous to let the caller decide if any fancy argument quoting is needed."

My view is, if such exceptions are not necessary with ``java.lang.ProcessBuilder`` they should not be necessary with ``com.zaxxer.nuprocess.NuProcessBuilder``.  It should just work, without the user having to contemplate.

**Comment by bhamiltoncx** [comment] 2015-09-18 13:17
The second example (commented out) should definitely work on win32, and we
have tests to cover it. I'll confirm this morning.

The first example should not work, since it is not quoted correctly.

java.lang.ProcessBuilder definitely gets quoting wrong on Win32. I think
it's good to have NuProcessBuilder handle the quoting, since the double
quote backslash escaping logic for arguments is totally Byzantine.

2015年9月17日(木) 21:26 Brett Wooldridge <notifications@github.com>:

**Comment by bhamiltoncx** [comment] 2015-09-18 19:48
So sorry. This was completely my fault. Reproduced, and fix is in https://github.com/brettwooldridge/NuProcess/pull/44 .

**Closed** 2015-09-19 13:58 UTC
