### ISSUE TITLE
NoSuchMethodError on Java8 JVM

### ISSUE THREAD

**Issue by madsvonqualen** [brettwooldridge/NuProcess#132] opened 2021-09-23 11:44 UTC
When using version 2.0.2 on a Java 8 JVM I get this exception:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
	at com.zaxxer.nuprocess.windows.WindowsProcess.afterStart(WindowsProcess.java:622)
	at com.zaxxer.nuprocess.windows.WindowsProcess.prepareProcess(WindowsProcess.java:308)
	at com.zaxxer.nuprocess.windows.WindowsProcess.start(WindowsProcess.java:232)
	at com.zaxxer.nuprocess.windows.WinProcessFactory.createProcess(WinProcessFactory.java:42)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:259)
```

According to https://github.com/eclipse/jetty.project/issues/3244#issuecomment-495322586 this is caused by compiling the code with JDK9+ while using the -source/-target flags instead og using the new -release flag.

This issue is not present in version 2.0.1.

**Comment by slandelle** [comment] 2021-09-23 11:46
Duplicate of #128

**Comment by bturner** [comment] 2022-02-07 22:27
Closing this as a duplicate of #128

**Closed by bturner** 2022-02-07 22:27 UTC
